### ISSUE TITLE
AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [hugmanrique/Twtr#2]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Just one format for all major distributions
- Works out of the box, no installation of runtimes needed (unlike Snap and Flatpak)
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs (unlike Flatpak)
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

[electron-builder](https://github.com/electron-userland/electron-builder) has native support for generating AppImages from Electron-based applications.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by hugmanrique** [comment]
As I say in the README.md, I did this project intending to learn how to use the Electron framework. That's the main cause why I don't provide AppImages or packages for other systems (such as Windows or macOS). The compilation of this packages is simple, and it's also explained in the README file. Indeed, this project uses electron-builder to compile itself into binary production-ready packages.
