### ISSUE TITLE
White block for password reset page

### ISSUE THREAD

**Issue by MxJesusDiaz** [hugmanrique/Twtr#5]
**The CSS of the section "Forgot Password" is broken.**
![screenshot_4](https://cloud.githubusercontent.com/assets/13721904/25318641/a26cce40-2858-11e7-9694-f80329719e90.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/13721904/25318642/a28f7ad0-2858-11e7-9251-199046508f73.png)

**Comment by raulsmartin** [comment]
Fixed at commit [dd8c98e](https://github.com/hugmanrique/Twtr/commit/dd8c98e98b3be00a97a4c48de2def751ae728efa)
